# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('sector', models.CharField(blank=True, max_length=1023, null=True)),
                ('branche', models.CharField(blank=True, max_length=1023, null=True)),
                ('body', models.CharField(blank=True, max_length=1023, null=True)),
                ('info_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'info_table',
            },
        ),
        migrations.CreateModel(
            name='Prognose',
            fields=[
                ('sector', models.CharField(blank=True, max_length=1023, null=True)),
                ('branche', models.CharField(blank=True, max_length=1023, null=True)),
                ('head', models.CharField(blank=True, max_length=1023, null=True)),
                ('body', models.CharField(blank=True, max_length=1023, null=True)),
                ('prog_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'prog_table',
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('sector', models.CharField(blank=True, max_length=1023, null=True)),
                ('branche', models.CharField(blank=True, max_length=1023, null=True)),
                ('head', models.CharField(blank=True, max_length=1023, null=True)),
                ('body', models.CharField(blank=True, max_length=1023, null=True)),
                ('trend_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'trend_table',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
