# Generated by Django 2.0.1 on 2018-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevEffect',
            fields=[
                ('body', models.CharField(blank=True, max_length=1023, null=True)),
                ('dev_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dev_eff_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devel_for_branche',
            fields=[
                ('branche', models.CharField(blank=True, max_length=1023, null=True)),
                ('devel_id', models.IntegerField()),
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'devel_for_branche',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('development', models.CharField(blank=True, max_length=1023, null=True)),
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'development_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrognoseEffect',
            fields=[
                ('body', models.CharField(blank=True, max_length=1023, null=True)),
                ('prog_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prog_eff_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requested_Dev',
            fields=[
                ('development', models.CharField(blank=True, max_length=1023, null=True)),
                ('user', models.CharField(blank=True, max_length=1023, null=True)),
                ('date', models.CharField(blank=True, max_length=1023, null=True)),
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'requested_developments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('developments', models.CharField(blank=True, max_length=1023, null=True)),
                ('user', models.CharField(blank=True, max_length=1023, null=True)),
                ('date_created', models.CharField(blank=True, max_length=1023, null=True)),
                ('date_estimated', models.CharField(blank=True, max_length=1023, null=True)),
                ('turn_over', models.IntegerField()),
                ('ebitda', models.IntegerField()),
                ('bruto_margin', models.IntegerField()),
                ('liquidity', models.IntegerField()),
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'scenario_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendEffect',
            fields=[
                ('body', models.CharField(blank=True, max_length=1023, null=True)),
                ('trend_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trend_eff_table',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
